[2024-04-09T16:04:00.438+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.1120 scheduled__2024-04-09T15:58:50.277723+00:00 [queued]>
[2024-04-09T16:04:00.446+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.1120 scheduled__2024-04-09T15:58:50.277723+00:00 [queued]>
[2024-04-09T16:04:00.447+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T16:04:00.590+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 1120> on 2024-04-09 15:58:50.277723+00:00
[2024-04-09T16:04:00.596+0000] {standard_task_runner.py:60} INFO - Started process 642 to run task
[2024-04-09T16:04:00.600+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '1120', 'scheduled__2024-04-09T15:58:50.277723+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp2xog445z']
[2024-04-09T16:04:00.603+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask 1120
[2024-04-09T16:04:00.647+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.1120 scheduled__2024-04-09T15:58:50.277723+00:00 [running]> on host dcb7ab325c84
[2024-04-09T16:04:00.727+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='1120' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T15:58:50.277723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T15:58:50.277723+00:00'
[2024-04-09T16:04:00.862+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'success', 'data': 'Sinh hoạt đầu khóa dành cho các lớp Cao học K13A', 'message': 'Data inserted'}
[2024-04-09T16:04:00.888+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=1120, execution_date=20240409T155850, start_date=20240409T160400, end_date=20240409T160400
[2024-04-09T16:04:00.932+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T16:04:00.957+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
