[2024-04-09T16:41:33.491+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.1200 manual__2024-04-09T16:41:18.377620+00:00 [queued]>
[2024-04-09T16:41:33.504+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.1200 manual__2024-04-09T16:41:18.377620+00:00 [queued]>
[2024-04-09T16:41:33.505+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T16:41:33.678+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 1200> on 2024-04-09 16:41:18.377620+00:00
[2024-04-09T16:41:33.685+0000] {standard_task_runner.py:60} INFO - Started process 1834 to run task
[2024-04-09T16:41:33.690+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '1200', 'manual__2024-04-09T16:41:18.377620+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpst5un_ee']
[2024-04-09T16:41:33.693+0000] {standard_task_runner.py:88} INFO - Job 170: Subtask 1200
[2024-04-09T16:41:33.742+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.1200 manual__2024-04-09T16:41:18.377620+00:00 [running]> on host dcb7ab325c84
[2024-04-09T16:41:33.824+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='1200' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T16:41:18.377620+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-09T16:41:18.377620+00:00'
[2024-04-09T16:41:33.931+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Vector inserting error: expected dim: 1536, got 0"},"time":0.014756259}\''}
[2024-04-09T16:41:33.965+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=1200, execution_date=20240409T164118, start_date=20240409T164133, end_date=20240409T164133
[2024-04-09T16:41:34.023+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T16:41:34.051+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
