[2024-04-09T12:26:02.682+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.2112 scheduled__2024-04-09T12:16:29.101242+00:00 [queued]>
[2024-04-09T12:26:02.703+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.2112 scheduled__2024-04-09T12:16:29.101242+00:00 [queued]>
[2024-04-09T12:26:02.705+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T12:26:02.735+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2112> on 2024-04-09 12:16:29.101242+00:00
[2024-04-09T12:26:02.754+0000] {standard_task_runner.py:60} INFO - Started process 160 to run task
[2024-04-09T12:26:02.810+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '2112', 'scheduled__2024-04-09T12:16:29.101242+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmph4v0whvl']
[2024-04-09T12:26:02.848+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask 2112
[2024-04-09T12:26:04.201+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.2112 scheduled__2024-04-09T12:16:29.101242+00:00 [running]> on host 4b0cf5e8e48f
[2024-04-09T12:26:04.333+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='2112' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T12:16:29.101242+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T12:16:29.101242+00:00'
[2024-04-09T12:26:05.002+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Collection `21120051` already exists!"},"time":0.489645138}\''}
[2024-04-09T12:26:05.071+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=2112, execution_date=20240409T121629, start_date=20240409T122602, end_date=20240409T122605
[2024-04-09T12:26:05.172+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T12:26:05.562+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
