[2024-04-09T23:55:03.367+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.2112 scheduled__2024-04-09T23:35:40.894562+00:00 [queued]>
[2024-04-09T23:55:03.378+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.2112 scheduled__2024-04-09T23:35:40.894562+00:00 [queued]>
[2024-04-09T23:55:03.378+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T23:55:03.395+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2112> on 2024-04-09 23:35:40.894562+00:00
[2024-04-09T23:55:03.402+0000] {standard_task_runner.py:60} INFO - Started process 112 to run task
[2024-04-09T23:55:03.410+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '2112', 'scheduled__2024-04-09T23:35:40.894562+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp0487cosb']
[2024-04-09T23:55:03.414+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask 2112
[2024-04-09T23:55:03.944+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.2112 scheduled__2024-04-09T23:35:40.894562+00:00 [running]> on host 083da196de81
[2024-04-09T23:55:04.025+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='2112' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T23:35:40.894562+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T23:35:40.894562+00:00'
[2024-04-09T23:55:04.336+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Collection `21120051` already exists!"},"time":0.204818835}\''}
[2024-04-09T23:55:04.361+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=2112, execution_date=20240409T233540, start_date=20240409T235503, end_date=20240409T235504
[2024-04-09T23:55:04.426+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T23:55:04.697+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
