[2024-04-10T13:53:15.825+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.1200 manual__2024-04-10T13:53:00.152355+00:00 [queued]>
[2024-04-10T13:53:15.835+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.1200 manual__2024-04-10T13:53:00.152355+00:00 [queued]>
[2024-04-10T13:53:15.836+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-10T13:53:16.000+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 1200> on 2024-04-10 13:53:00.152355+00:00
[2024-04-10T13:53:16.007+0000] {standard_task_runner.py:60} INFO - Started process 531 to run task
[2024-04-10T13:53:16.012+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '1200', 'manual__2024-04-10T13:53:00.152355+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp0ls9qxkb']
[2024-04-10T13:53:16.015+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask 1200
[2024-04-10T13:53:16.068+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.1200 manual__2024-04-10T13:53:00.152355+00:00 [running]> on host c34bafd0ff75
[2024-04-10T13:53:16.151+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='1200' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T13:53:00.152355+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-10T13:53:00.152355+00:00'
[2024-04-10T13:53:16.262+0000] {logging_mixin.py:188} INFO - Document with id 661699c83b0bac9af006f4fb has been indexed
[2024-04-10T13:53:16.273+0000] {logging_mixin.py:188} INFO - Document with id 661699ca030de90c3943edf5 has been indexed
[2024-04-10T13:53:16.276+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'success', 'message': 'Data inserted into Qdrant', 'updated_ids': [ObjectId('661699c83b0bac9af006f4fb'), ObjectId('661699ca030de90c3943edf5')]}
[2024-04-10T13:53:16.291+0000] {xcom.py:664} ERROR - Object of type ObjectId is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-04-10T13:53:16.303+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bson.objectid.ObjectId'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 451, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3010, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2024-04-10T13:53:16.333+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=21120051, task_id=1200, execution_date=20240410T135300, start_date=20240410T135315, end_date=20240410T135316
[2024-04-10T13:53:16.357+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task 1200 (Object of type ObjectId is not JSON serializable; 531)
[2024-04-10T13:53:16.384+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-10T13:53:16.425+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
